
package Main;

import Metodos_SQL.Metodos_sql;
import java.awt.Color;
import javax.swing.JOptionPane;


public class Frm_login extends javax.swing.JFrame {

    /**
     * Creates new form Frm_login
     */
    public Frm_login() {
        initComponents();
        setLocationRelativeTo(null);
    }
    Metodos_sql metodos = new Metodos_sql();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPasswordField_contraseña = new javax.swing.JPasswordField();
        jButton_entrar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();
        jTextField_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordField_contraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordField_contraseña.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField_contraseña.setText("********");
        jPasswordField_contraseña.setBorder(null);
        jPasswordField_contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField_contraseñaMousePressed(evt);
            }
        });
        jPasswordField_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_contraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 240, 20));

        jButton_entrar.setBackground(new java.awt.Color(0, 153, 255));
        jButton_entrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_entrar.setText("Ingresar");
        jButton_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_entrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 166, -1));

        jButton_cancelar.setBackground(new java.awt.Color(0, 153, 255));
        jButton_cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png"))); // NOI18N
        jButton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 27, -1));

        jTextField_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_usuario.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_usuario.setText("Ingrese su nombre de usuario");
        jTextField_usuario.setBorder(null);
        jTextField_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_usuarioMousePressed(evt);
            }
        });
        jTextField_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 240, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("USUARIO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CONTRASEÑA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("INICIAR SESIÓN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimizar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 32, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 28, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Acceder.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 130, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LoginFondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 350, 490));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoResize.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 40, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("RememberMe");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 240, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 240, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarActionPerformed
        //Con el boton cancelar nos regresa al menu
        Frm_menu ventana = new Frm_menu();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_cancelarActionPerformed

    private void jButton_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_entrarActionPerformed
        String busqueda_uResgistrado = metodos.BuscarUsuarioRegistrado(jTextField_usuario.getText(), jPasswordField_contraseña.getText());
        if(jTextField_usuario.getText().equals("root")&&jPasswordField_contraseña.getText().equals("root")){
            JOptionPane.showMessageDialog(null, "Iniciaste como Admin");
            
            Frm_sistema ventana = new Frm_sistema();//aca le deberia meter la contra(jPasswordField_contraseña.getText())
            ventana.jLabel_nombreSistema.setText("Eres Admin");
            ventana.setVisible(true);
            
            this.dispose();
            
        }else if(busqueda_uResgistrado.equals("Usuario registrado")){
            //Quepasa si estoy en la base de datos
            String busqueda_usuario = metodos.buscarUsuario(jTextField_usuario.getText());
            
            String user = jTextField_usuario.getText();
            
            JOptionPane.showMessageDialog(this, "Bienvenido(a)"+busqueda_usuario);
            
            Frm_sistema ventana = new Frm_sistema();//aca le deberia meter la contra
            
            
            ventana.jLabel_nombreSistema.setText(busqueda_usuario);//colocamos nombre en label
            
            //Usar el id y mostrarlo
            String busqueda_id = metodos.buscarId(jTextField_usuario.getText());
            
            ventana.jLabel_idUsuario.setText(busqueda_id);
            ventana.jLabel_user.setText(user);
                    
            ventana.setVisible(true);
            
            
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No estas registrado, por favor registrate");
        }
        
    }//GEN-LAST:event_jButton_entrarActionPerformed

    private void jTextField_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usuarioActionPerformed
        
    }//GEN-LAST:event_jTextField_usuarioActionPerformed

    private void jPasswordField_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_contraseñaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setExtendedState(ICONIFIED);//minimizar
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_usuarioMousePressed
       if(jTextField_usuario.getText().equals("Ingrese su nombre de usuario")){
          jTextField_usuario.setText("");
          jTextField_usuario.setForeground(Color.black);
       }
       if(String.valueOf(jPasswordField_contraseña.getPassword()).isEmpty()){
          jPasswordField_contraseña.setText("********");
          jPasswordField_contraseña.setForeground(Color.gray);
       }
       
    }//GEN-LAST:event_jTextField_usuarioMousePressed

    private void jPasswordField_contraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_contraseñaMousePressed
       if(String.valueOf(jPasswordField_contraseña.getPassword()).equals("********")){
           jPasswordField_contraseña.setText("");
           jPasswordField_contraseña.setForeground(Color.black);
       }
       if(jTextField_usuario.getText().isEmpty()){
           jTextField_usuario.setText("Ingrese su nombre de usuario");
           jTextField_usuario.setForeground(Color.gray);
       }
    
    }//GEN-LAST:event_jPasswordField_contraseñaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JButton jButton_entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_contraseña;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JTextField jTextField_usuario;
    // End of variables declaration//GEN-END:variables
}
