package Main;

import Metodos_SQL.Metodos_sql;
import java.awt.Color;
import javax.swing.JOptionPane;

public class Frm_añadirUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Frm_añadirUsuario
     */
    public Frm_añadirUsuario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    Metodos_sql metodos = new Metodos_sql();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_usuario = new javax.swing.JTextField();
        jButton_Registrar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jPasswordField_contraseña = new javax.swing.JPasswordField();
        jTextField_apellido = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(661, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRAR USUARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 26));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("USUARIO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 69, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CONTRASEÑA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jTextField_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_usuario.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_usuario.setText("Ingrese un nombre de usuario");
        jTextField_usuario.setBorder(null);
        jTextField_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_usuarioMousePressed(evt);
            }
        });
        jPanel1.add(jTextField_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 270, 20));

        jButton_Registrar.setBackground(new java.awt.Color(0, 153, 255));
        jButton_Registrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Registrar.setText("Registrar");
        jButton_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 130, -1));

        jButton_cancelar.setBackground(new java.awt.Color(0, 153, 255));
        jButton_cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png"))); // NOI18N
        jButton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 28, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("APELLIDO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("NOMBRE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jTextField_nombre.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_nombre.setText("Ingrese su nombre");
        jTextField_nombre.setBorder(null);
        jTextField_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_nombreMousePressed(evt);
            }
        });
        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 270, 20));

        jPasswordField_contraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPasswordField_contraseña.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField_contraseña.setText("********");
        jPasswordField_contraseña.setBorder(null);
        jPasswordField_contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField_contraseñaMousePressed(evt);
            }
        });
        jPasswordField_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_contraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 270, 20));

        jTextField_apellido.setForeground(new java.awt.Color(204, 204, 204));
        jTextField_apellido.setText("Ingrese su apellido");
        jTextField_apellido.setBorder(null);
        jTextField_apellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_apellidoMousePressed(evt);
            }
        });
        jTextField_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_apellidoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 270, 20));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimizar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 30, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 32, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrarse.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 130, 149));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AñadirUsuarioFondo.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 0, 300, 470));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoResize.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 40, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("RememberMe");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 270, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 270, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 270, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 270, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarActionPerformed
        //Con el boton cancelar nos regresa al menu
        Frm_menu ventana = new Frm_menu();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_cancelarActionPerformed

    private void jButton_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarActionPerformed
        //añadir usuario
        if (jTextField_nombre.getText().equals("Ingrese su nombre")
                || jTextField_apellido.getText().equals("Ingrese su apellido")
                || jTextField_usuario.getText().equals("Ingrese un nombre de usuario")
                || jPasswordField_contraseña.getText().equals("********")
                || jTextField_nombre.getText().equals("")
                || jTextField_apellido.getText().equals("")
                || jTextField_usuario.getText().equals("")
                || jPasswordField_contraseña.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios");

        } else {
            //si ya esta registrado no se guarda
            if (metodos.existeUsuario(jTextField_usuario.getText()) == 0) {//si es 0 no existe
                int i = metodos.guardar(jTextField_nombre.getText(), jTextField_apellido.getText(), jTextField_usuario.getText(), jPasswordField_contraseña.getText());
                if (i > 0) {//si i tiene parametros añadidos
                    JOptionPane.showMessageDialog(this, "Datos registrados en el sistema");
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo registrar el usuario nuevo");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Este usuario ya existe, digite otro nombre de usuario.");
            }
        }
        /*JOptionPane.showMessageDialog(null, "Este usuario ya a sido registrado");*/
    }//GEN-LAST:event_jButton_RegistrarActionPerformed

    private void jPasswordField_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_contraseñaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setExtendedState(ICONIFIED);//minimizar
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_apellidoActionPerformed

    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    private void jTextField_nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_nombreMousePressed
        if (jTextField_nombre.getText().equals("Ingrese su nombre")) {
            jTextField_nombre.setText("");
            jTextField_nombre.setForeground(Color.black);
        }
        if (jTextField_apellido.getText().isEmpty()) {
            jTextField_apellido.setText("Ingrese su apellido");
            jTextField_apellido.setForeground(Color.gray);
        }
        if (jTextField_usuario.getText().isEmpty()) {
            jTextField_usuario.setText("Ingrese un nombre de usuario");
            jTextField_usuario.setForeground(Color.gray);
        }
        if (String.valueOf(jPasswordField_contraseña.getPassword()).isEmpty()) {
            jPasswordField_contraseña.setText("********");
            jPasswordField_contraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextField_nombreMousePressed

    private void jTextField_apellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_apellidoMousePressed

        if (jTextField_apellido.getText().equals("Ingrese su apellido")) {
            jTextField_apellido.setText("");
            jTextField_apellido.setForeground(Color.black);
        }

        if (jTextField_nombre.getText().isEmpty()) {
            jTextField_nombre.setText("Ingrese su nombre");
            jTextField_nombre.setForeground(Color.gray);
        }

        if (jTextField_usuario.getText().isEmpty()) {
            jTextField_usuario.setText("Ingrese un nombre de usuario");
            jTextField_usuario.setForeground(Color.gray);
        }
        if (String.valueOf(jPasswordField_contraseña.getPassword()).isEmpty()) {
            jPasswordField_contraseña.setText("********");
            jPasswordField_contraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextField_apellidoMousePressed

    private void jTextField_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_usuarioMousePressed

        if (jTextField_usuario.getText().equals("Ingrese un nombre de usuario")) {
            jTextField_usuario.setText("");
            jTextField_usuario.setForeground(Color.black);
        }
        if (jTextField_apellido.getText().isEmpty()) {
            jTextField_apellido.setText("Ingrese su apellido");
            jTextField_apellido.setForeground(Color.gray);
        }

        if (jTextField_nombre.getText().isEmpty()) {
            jTextField_nombre.setText("Ingrese su nombre");
            jTextField_nombre.setForeground(Color.gray);
        }

        if (String.valueOf(jPasswordField_contraseña.getPassword()).isEmpty()) {
            jPasswordField_contraseña.setText("********");
            jPasswordField_contraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextField_usuarioMousePressed

    private void jPasswordField_contraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_contraseñaMousePressed

        if (String.valueOf(jPasswordField_contraseña.getPassword()).equals("********")) {
            jPasswordField_contraseña.setText("");
            jPasswordField_contraseña.setForeground(Color.black);
        }
        if (jTextField_nombre.getText().isEmpty()) {
            jTextField_nombre.setText("Ingrese su nombre");
            jTextField_nombre.setForeground(Color.gray);
        }

        if (jTextField_apellido.getText().isEmpty()) {
            jTextField_apellido.setText("Ingrese su apellido");
            jTextField_apellido.setForeground(Color.gray);
        }

        if (jTextField_usuario.getText().isEmpty()) {
            jTextField_usuario.setText("Ingrese un nombre de usuario");
            jTextField_usuario.setForeground(Color.gray);
        }

    }//GEN-LAST:event_jPasswordField_contraseñaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_añadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_añadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_añadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_añadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_añadirUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Registrar;
    private javax.swing.JButton jButton_cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_contraseña;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField_apellido;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_usuario;
    // End of variables declaration//GEN-END:variables
}
